In [1]:
from traceback import print_tb

import numpy as np

In [2]:
li = [1,2,3,4,5,6]
print(type(li))
print(li)
ar = np.array((1,2,3,4,5,6))
print(type(ar))
print(ar)

<class 'list'>
[1, 2, 3, 4, 5, 6]
<class 'numpy.ndarray'>
[1 2 3 4 5 6]


In [56]:
import timeit
import numpy as np

# Setup: 1 million elements
size = 1000000
setup = f"import numpy as np; my_list = list(range({size})); my_arr = np.arange({size})"

# List operation: Square each number (list comprehension)
list_time = timeit.timeit("[x**2 for x in my_list]", setup=setup, number=10)

# Array operation: Square each number (vectorized)
arr_time = timeit.timeit("my_arr**2", setup=setup, number=10)

print(f"List time: {list_time:.5f}s")
print(f"Array time: {arr_time:.5f}s")
print(f"Array is {list_time/arr_time:.2f}x faster")


List time: 1.97118s
Array time: 0.00368s
Array is 535.65x faster


In [4]:
li = [1,2,3,4,5,6]

arr = np.array(li)
print(arr+2)

[3 4 5 6 7 8]


In [5]:
arr = np.array(range(0,5),ndmin=9)
print(arr)
print(arr.ndim)

[[[[[[[[[0 1 2 3 4]]]]]]]]]
9


In [6]:
li = [[1,2,3],[4,5,6]]
arr2D = np.array([[1,2,3],[4,5,6]])

In [7]:
arr2D

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
import numpy as np


In [9]:
li = [1,2,3,4,5,6]
print(li)
print((type(li)))
ar = np.array(li)
print(ar)
print((type(ar)))

[1, 2, 3, 4, 5, 6]
<class 'list'>
[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [10]:
for i in range(0,6):
    print(li[i])
    print(ar[i])

1
1
2
2
3
3
4
4
5
5
6
6


In [11]:
arr = np.array(range(0,10),ndmin=2)


In [12]:
arr

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [13]:
arr.ndim

2

In [19]:
arr.shape

(1, 10)

In [20]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
# arr2D = np.array([[[[1,2,3,4,5],[5,6,7,8,6],[5,6,7,8,6]],[[5,6,7,8,6],[1,2,3,4,6],[5,6,7,8,7]]],[[[5,6,7,8,6],[1,2,3,4,5],[5,6,7,8,6]],[[1,2,3,4,6],[5,6,7,8,7]]]])

In [24]:

arr2D

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
arr2D.ndim

2

In [26]:
arr2D.shape

(2, 3)

In [27]:
arr2D = np.array(range(0,60)).reshape(2,3,2,5)

In [28]:
arr2D


array([[[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]],


       [[[30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49]],

        [[50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]]])

In [29]:
arr2D.shape

(2, 3, 2, 5)

In [30]:
arr2D = np.array(range(72))

In [31]:
arr2D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71])

In [32]:
arr2D.reshape(2,2,3,6)

array([[[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11],
         [12, 13, 14, 15, 16, 17]],

        [[18, 19, 20, 21, 22, 23],
         [24, 25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34, 35]]],


       [[[36, 37, 38, 39, 40, 41],
         [42, 43, 44, 45, 46, 47],
         [48, 49, 50, 51, 52, 53]],

        [[54, 55, 56, 57, 58, 59],
         [60, 61, 62, 63, 64, 65],
         [66, 67, 68, 69, 70, 71]]]])

In [33]:
arr0 = np.identity(5)

In [34]:
arr0 = np.zeros((2,5))

In [35]:
arr0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [36]:
arrCopied = arr0.copy()

In [37]:
arrCopied

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
arr = np.zeros((2,2,3,4,5))
# arr.reshape(2,2,3,4,5)

In [43]:
arr

array([[[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]],



       [[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0

In [44]:
arr.ndim

5

In [82]:
arr= np.array(range(240))

In [47]:
arr.ndim


1

In [50]:
arr2 = arr.reshape(2,2,3,4,5)

In [52]:
arr2.ndim

5

In [53]:
li = [1,2,3,4,5]
arra = np.array([1,2,3,4,5])

In [54]:
li

[1, 2, 3, 4, 5]

In [55]:
arra

array([1, 2, 3, 4, 5])

In [57]:
ar = np.array(range(0,10))

In [59]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
ar.shape

(10,)

In [62]:
ar.ndim

1

In [68]:
arr2D = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [69]:
arr2D

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [70]:
arr2D.ndim

3

In [71]:
arr2D.shape

(2, 2, 3)

In [72]:
li = ["Ahmad","Ali","Mohammad","Sara","Mohammed","Ali"]
arr = np.array(li)

In [73]:
arr

array(['Ahmad', 'Ali', 'Mohammad', 'Sara', 'Mohammed', 'Ali'], dtype='<U8')

In [75]:
for name in arr:
    print(name)

Ahmad
Ali
Mohammad
Sara
Mohammed
Ali


In [76]:
numericList = [1,2,3,4,5,6]
numericArray = np.array(range(0,6))

In [77]:
numericArray

array([0, 1, 2, 3, 4, 5])

In [78]:
numericList

[1, 2, 3, 4, 5, 6]

In [80]:
for i in numericArray:
    print(i**2)

0
1
4
9
16
25


In [81]:
print(numericArray**2)

[ 0  1  4  9 16 25]


In [84]:
arr = arr.reshape(2,2,3,4,5)

In [86]:
arr = np.array(range(0,10))

In [87]:
arr = arr.reshape(2,5)

In [88]:
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [89]:
arr.shape

(2, 5)

In [90]:
arr[1,2]

np.int64(7)

In [93]:
numericArray[5]

np.int64(5)

In [94]:
tArr = np.array(range(8))

In [95]:
tArr = tArr.reshape(2,2,2)

In [96]:
tArr

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [98]:
tArr[1,0,1]

np.int64(5)

In [99]:
farr = np.array(range(240))

In [100]:
farr = farr.reshape(2,2,3,4,5)

In [101]:
farr
#177
#71
#240
#0

array([[[[[  0,   1,   2,   3,   4],
          [  5,   6,   7,   8,   9],
          [ 10,  11,  12,  13,  14],
          [ 15,  16,  17,  18,  19]],

         [[ 20,  21,  22,  23,  24],
          [ 25,  26,  27,  28,  29],
          [ 30,  31,  32,  33,  34],
          [ 35,  36,  37,  38,  39]],

         [[ 40,  41,  42,  43,  44],
          [ 45,  46,  47,  48,  49],
          [ 50,  51,  52,  53,  54],
          [ 55,  56,  57,  58,  59]]],


        [[[ 60,  61,  62,  63,  64],
          [ 65,  66,  67,  68,  69],
          [ 70,  71,  72,  73,  74],
          [ 75,  76,  77,  78,  79]],

         [[ 80,  81,  82,  83,  84],
          [ 85,  86,  87,  88,  89],
          [ 90,  91,  92,  93,  94],
          [ 95,  96,  97,  98,  99]],

         [[100, 101, 102, 103, 104],
          [105, 106, 107, 108, 109],
          [110, 111, 112, 113, 114],
          [115, 116, 117, 118, 119]]]],



       [[[[120, 121, 122, 123, 124],
          [125, 126, 127, 128, 129],
          [130, 131,