In [3]:
from traceback import print_tb

import numpy as np

In [9]:
li = [1,2,3,4,5,6]
print(type(li))
print(li)
ar = np.array((1,2,3,4,5,6))
print(type(ar))
print(ar)

<class 'list'>
[1, 2, 3, [4, 5], 6]
<class 'numpy.ndarray'>
[1 2 3 4 5 6]


In [7]:
import timeit
import numpy as np

# Setup: 1 million elements
size = 1000000
setup = f"import numpy as np; my_list = list(range({size})); my_arr = np.arange({size})"

# List operation: Square each number (list comprehension)
list_time = timeit.timeit("[x**2 for x in my_list]", setup=setup, number=10)

# Array operation: Square each number (vectorized)
arr_time = timeit.timeit("my_arr**2", setup=setup, number=10)

print(f"List time: {list_time:.5f}s")
print(f"Array time: {arr_time:.5f}s")
print(f"Array is {list_time/arr_time:.2f}x faster")


List time: 1.97489s
Array time: 0.00470s
Array is 419.99x faster


In [21]:
li = [1,2,3,4,5,6]

arr = np.array(li)
print(arr+2)

[3 4 5 6 7 8]


In [26]:
arr = np.array(range(0,5),ndmin=9)
print(arr)
print(arr.ndim)

[[[[[[[[[0 1 2 3 4]]]]]]]]]
9


In [30]:
li = [[1,2,3],[4,5,6]]
arr2D = np.array([[1,2,3],[4,5,6]])

In [31]:
arr2D

array([[1, 2, 3],
       [4, 5, 6]])