In [1]:
from traceback import print_tb

import numpy as np

In [9]:
li = [1,2,3,4,5,6]
print(type(li))
print(li)
ar = np.array((1,2,3,4,5,6))
print(type(ar))
print(ar)

<class 'list'>
[1, 2, 3, [4, 5], 6]
<class 'numpy.ndarray'>
[1 2 3 4 5 6]


In [8]:
import timeit
import numpy as np

# Setup: 1 million elements
size = 1000000
setup = f"import numpy as np; my_list = list(range({size})); my_arr = np.arange({size})"

# List operation: Square each number (list comprehension)
list_time = timeit.timeit("[x**2 for x in my_list]", setup=setup, number=10)

# Array operation: Square each number (vectorized)
arr_time = timeit.timeit("my_arr**2", setup=setup, number=10)

print(f"List time: {list_time:.5f}s")
print(f"Array time: {arr_time:.5f}s")
print(f"Array is {list_time/arr_time:.2f}x faster")


List time: 1.97107s
Array time: 0.00410s
Array is 480.67x faster


In [21]:
li = [1,2,3,4,5,6]

arr = np.array(li)
print(arr+2)

[3 4 5 6 7 8]


In [26]:
arr = np.array(range(0,5),ndmin=9)
print(arr)
print(arr.ndim)

[[[[[[[[[0 1 2 3 4]]]]]]]]]
9


In [30]:
li = [[1,2,3],[4,5,6]]
arr2D = np.array([[1,2,3],[4,5,6]])

In [31]:
arr2D

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
import numpy as np


In [5]:
li = [1,2,3,4,5,6]
print(li)
print((type(li)))
ar = np.array(li)
print(ar)
print((type(ar)))

[1, 2, 3, 4, 5, 6]
<class 'list'>
[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [7]:
for i in range(0,6):
    print(li[i])
    print(ar[i])

1
1
2
2
3
3
4
4
5
5
6
6


In [17]:
arr = np.array(range(0,10),ndmin=2)


In [18]:
arr

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [19]:
arr.ndim

2

In [20]:
arr.shape

(1, 10)

In [21]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
arr2D = np.array([[[[1,2,3,4,5],[5,6,7,8,6],[5,6,7,8,6]],[[5,6,7,8,6],[1,2,3,4,6],[5,6,7,8,7]]],[[[5,6,7,8,6],[1,2,3,4,5],[5,6,7,8,6]],[[1,2,3,4,6],[5,6,7,8,7]]]])

In [34]:

arr2D

array([[[[1, 2, 3, 4, 5],
         [5, 6, 7, 8, 6]],

        [[1, 2, 3, 4, 6],
         [5, 6, 7, 8, 7]]],


       [[[1, 2, 3, 4, 5],
         [5, 6, 7, 8, 6]],

        [[1, 2, 3, 4, 6],
         [5, 6, 7, 8, 7]]]])

In [35]:
arr2D.ndim

4

In [36]:
arr2D.shape

(2, 2, 2, 5)

In [37]:
arr2D = np.array(range(0,60)).reshape(2,3,2,5)

In [38]:
arr2D


array([[[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]],


       [[[30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49]],

        [[50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]]])

In [39]:
arr2D.shape

(2, 3, 2, 5)

In [43]:
arr2D = np.array(range(72))

In [44]:
arr2D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71])

In [46]:
arr2D.reshape(2,2,3,6)

array([[[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11],
         [12, 13, 14, 15, 16, 17]],

        [[18, 19, 20, 21, 22, 23],
         [24, 25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34, 35]]],


       [[[36, 37, 38, 39, 40, 41],
         [42, 43, 44, 45, 46, 47],
         [48, 49, 50, 51, 52, 53]],

        [[54, 55, 56, 57, 58, 59],
         [60, 61, 62, 63, 64, 65],
         [66, 67, 68, 69, 70, 71]]]])

In [62]:
arr0 = np.identity(5)

In [56]:
arr0 = np.zeros((2,5))

In [63]:
arr0

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [58]:
arrCopied = arr0.copy()

In [59]:
arrCopied

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])